universe = vanilla
executable = condor_run.sh
error = $(Cluster).$(Process).condor_mfcl.err
log = $(Cluster).$(Process).condor_mfcl.log
output = $(Cluster).$(Process).condor_mfcl.out
requirements = (OpSys == "LINUX")
request_memory = 7600
request_disk = 5500000
when_to_transfer_output = ON_EXIT
should_transfer_files = YES
transfer_input_files = Start.tar.gz
transfer_output_files = End.tar.gz
queue
